//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotation
    {
        public long ID { get; set; }
        public long SourceID { get; set; }
        public string Annotator_schema_version { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Text { get; set; }
        public string Quote { get; set; }
        public string Uri { get; set; }
        public string Ranges { get; set; }
        public Nullable<long> User { get; set; }
        public string Consumer { get; set; }
        public string Tags { get; set; }
        public string Permissions { get; set; }
    
        public virtual Source Source { get; set; }
    }
}
