//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotation
    {
        public int ID { get; set; }
        public string Updated { get; set; }
        public string Target { get; set; }
        public string Created { get; set; }
        public string Text { get; set; }
        public string Tags { get; set; }
        public string Uri { get; set; }
        public string Document { get; set; }
        public string Consumer { get; set; }
        public string Permissions { get; set; }
        public string User { get; set; }
        public int UserID { get; set; }
        public Nullable<long> SourceID { get; set; }
    }
}
