//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.Sources = new HashSet<Source>();
        }
    
        public byte[] name { get; set; }
        public long ID { get; set; }
        public string description { get; set; }
        public long parentID { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<long> userID { get; set; }
    
        public virtual ICollection<Source> Sources { get; set; }
        public virtual User User { get; set; }
    }
}
