//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.SourceTags = new HashSet<SourceTag>();
        }
    
        public long ID { get; set; }
        public long UserID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> ReadLater { get; set; }
        public Nullable<bool> SaveOffline { get; set; }
        public Nullable<bool> Privacy { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string TagNames { get; set; }
        public string TagIDs { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SourceTag> SourceTags { get; set; }
    }
}
