//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.SourceTags = new HashSet<SourceTag>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public long ParentID { get; set; }
        public long UserID { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SourceTag> SourceTags { get; set; }
    }
}
