//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Annotations = new HashSet<Annotation>();
            this.Folders = new HashSet<Folder>();
            this.SourceUsers = new HashSet<SourceUser>();
            this.UserTagUsages = new HashSet<UserTagUsage>();
            this.Follows = new HashSet<Follow>();
            this.Follows1 = new HashSet<Follow>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
        }
    
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Identifier { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string Email { get; set; }
        public string Provider { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public bool UnsubscribeNotification { get; set; }
    
        public virtual ICollection<Annotation> Annotations { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual ICollection<SourceUser> SourceUsers { get; set; }
        public virtual ICollection<UserTagUsage> UserTagUsages { get; set; }
        public virtual ICollection<Follow> Follows { get; set; }
        public virtual ICollection<Follow> Follows1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Notification> Notifications1 { get; set; }
    }
}
