//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTagUsage
    {
        public long ID { get; set; }
        public long userID { get; set; }
        public long tagID { get; set; }
        public System.DateTime lastUsed { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
